### PR TITLE
Window Physics

### PR DESCRIPTION
**Pull request by niboty**
My take on Kitboga's famous gravity ahk script. Includes real accelerating gravity, bouncing, friction and the ability to throw windows.

### CODE REVIEW

**Comment by niboty** [comment]
Let me know if I did anything wrong with this pull request. Only used github on a few projects multiple years ago and everything was basically set up for me.

**Comment by niboty** [comment]
This is just the functionality for the physics as well. To actually use against scammers it probably needs a better quit key then esc, whatever it takes to hide it, and the disable maximize windows functionality.

**Comment by llamositopia** [comment]
Wow that is funny 😂 It's a little impractical for scambaiting, but hilarious nonetheless and a welcome addition to the repository. Just make sure you place your file in its own directory within the root directory. Like `<repo>/window-physics/WindowPhysics.ahk`

👍

**Comment by niboty** [comment]
Yeah okay, that makes sense, thanks!

**Pull request merged**
