### PR TITLE
added tree of death scripts

### PR DESCRIPTION
**Pull request by MelonSmasher**

### CODE REVIEW

**Comment by llamositopia** [comment]
Looks good 👍 provided this gets another 👍 I'll merge in

**Comment by llamositopia** [comment]
Optionally, could the random selector not select the tree bomb while it is considered dangerous? I'd rather it have a comment left in on how to include it rather than include it by default.

**Comment by MelonSmasher** [comment]
Yeah. I'll change that now.

**Comment by MelonSmasher** [comment]
This should not be merged in favor of #5. #5 is less hacky and has a safe fork bomb.

**Pull request closed without merging**
