### PR TITLE
E-Homoglyph

### PR DESCRIPTION
**Pull request by TheDevFreak**
New script i wrote to replace e-s with special e-s (U+0435) in cmd and run box.

### CODE REVIEW

**Comment by llamositopia** [comment]
Great idea but can this default to off instead of on?

**Comment by TheDevFreak** [comment]
@llamositopia Sorted!

**Comment by llamositopia** [comment]
👍 I'll just wait for a second pair of eyes before merging in

**Comment by TheDevFreak** [comment]
Sounds good!

**Comment by niboty** [comment]
I downloaded it and it works great for me. I love the idea too, it ruins netstat and tree without being obvious. Amazing

**Pull request merged**
